### ISSUE TITLE
What should the schema look like for results?

### ISSUE THREAD

**Issue by rhmdnd** [rhmdnd/compserv#84]
This project doesn't have a formal process for enhancements, so let's use an issue.

The goal of this issue is to understand what we need to write to persistent storage, and come up with a schema. Once we have agreement, we can port those schemas to the applicable open issues.

- [x] Define result schema
- [x] Define profile schema
- [x] Define a control schema
- [x] Define a catalog schema
- [x] Define an assessment schema
- [x] Define subject schema
- [x] Update subject schema to allow for hierarchical relationships
- [x] Define metadata schema
- [x] Determine how we want to store dates
- [x] Determine a consistent format for identifiers

## Terminology

`result` is the outcome of a compliance scan. It includes information like the outcome of the scan, the control the rule may be associated to, along with general information about the rule.

`subject` is the target of a scan, or the piece of infrastructure that was assessed.

`profile` is the baseline that results or rules refer to (e.g., NIST 800-53).

**Comment by rhmdnd** [comment]
I added the initial schema for 'subjects' in https://github.com/rhmdnd/compserv/commit/3b2d322b536975cbbfea7de3b966b87fd36242d8.

I'd like to keep it general, which is why there is only three columns (id, name, and type). An example would be `02b26437-0fb3-4d2a-b788-8c2b1cc640de`, `https://api.example..com`, `cluster`).

From there, we would have a foreign key to other tables that store the results (allowing us to query results by the cluster).

Thoughts?

**Comment by rhmdnd** [comment]
For results, I think we could start with `id`, `name`, `control`, `outcome`, and `description`.

## `id`

Required: True
Type: `UUID`
Exposed publicly: True

An RFC [4122](http://tools.ietf.org/html/rfc4122) UUID. We can use an existing go [module](https://github.com/google/uuid) to generate them, specifically UUID4 (which are randomly generated).

Should we expose an ID for each resource?

Is it safe to assume the gRPC API is going to expose a resource ID so that clients could call `compservClient.GetResult(resultId)`? If we allow clients to fetch all results, then allowing them to ask for a specific result feels completely reasonable. I think this makes a valid argument for exposing a unique identifier.

Related [reading](https://medium.com/@patrickfav/a-better-way-to-protect-your-database-ids-a33fa9867552).

## `name`

Required: True
Type: `VARCHAR(255)`
Exposed publicly: True

Must be the name of the rule (at least within the context of ComplianceAsCode/content rules). But it could be generalized to a unique name for any type of evaluation.

## `control`

Required: True
Type: `VARCHAR(50)` or a foreign key to a table dedicated to controls (`UUID`)
Exposed publicly: True

This could be something as simple as `NIST-AC02` or `cis@ocp4: 4.2.5`. In free form, this isn't very useful and it doesn't contain additional metadata about the control. Something else would need to fill in the gaps from a separate source of truth.

A more robust solution would to be to have a `UUID` that references the control, stored in a standard format (e.g., OSCAL) that would fill in the gaps.

The main point here, I think, would be to only include the control for the result. The result wouldn't contain any more information about the control than a reference to the control(s) it's related to.

## `outcome`

Required: True
Type: `VARCHAR(50)`
Exposed publicly: True

This seems like a good use case for a boolean, but the `outcome` could be one of several types (`passed`, `failed`, `not-applicable`, `manual`, etc.).

Is `VARCHAR(50)` appropriate for this? Is there a case where this type won't work for outcomes?

## `description`

Required: False
Type: `VARCHAR(255)`
Exposed publicly: True

This could be added on to the schema after, since it's not a required piece of information. The usage of this would really be up to the data ingestion process and what information it may need to set on the result. I'd be OK punting on this column until we have a clear use case for including it.

**Comment by rhmdnd** [comment]
# Subject schema

A `subject` is a generalized term for anything that can be scanned for compliance (a server, a piece of networking gear, a Kubernetes cluster, a private cloud, etc.)

## `id`

Required: True
Type: `UUID`
Exposed publicly: True

## `name`

Required: True
Type: `VARCHAR(255)`
Exposed publicly: True

A unique name for the subject. This could be a server host name or cluster name. We need some more thought here to see what makes this unique.

## `type`

Required: True
Type: `VARCHAR(50)`
Exposed publicly: True

Denotes the type of subject this is. This could be almost anything, but initially it would be a server or cluster. 

## `metadata_id`

Required: False
Type: `UUID`
Exposed publicly: False

This would be a foreign key to metadata.id table/column, used to link additional, common attributes to subjects (like created at and updated at times).

**Comment by JAORMX** [comment]
@rhmdnd should we make the subject be hierarchical? e.g. add a `parent_subject` column that may point to another subject? that would allow us to build sub-subjects. e.g.

Cluster:
`{id: 1, name: "cluster-a", type: "cluster", parent_id: null, ...}`

Control Plane Machine Pool:
`{id: 2, name: "control-plane", type: "machine-pool", parent_id: 1, ...}`

Worker Machine Pool:
`{id: 3, name: "workers", type: "machine-pool", parent_id: 1, ...}`

Node 1:
`{id: 4, name: "cluster-a-node-1", type: "node", parent_id: 2, ...}`

...

this way, it would be a lot easier to specify where stuff belongs to.

**Comment by JAORMX** [comment]
@rhmdnd I'm not so sure about the control being a `varchar(50)` ... as more compliance standards get evaluated, the number of references will grow. It's a matter of seeing how big the reference list already is in CaC. I also am not very keen on keeping a table just to reference different compliance standards... seems to me like a lot of duplication. So... I'd like to see if other folks have other ideas. @jhrozek anything on your side?

**Comment by rhmdnd** [comment]
Thanks for taking a look!

> @rhmdnd I'm not so sure about the control being a `varchar(50)` ... as more compliance standards get evaluated, the number of references will grow. It's a matter of seeing how big the reference list already is in CaC.

I'm not opposed to making this larger, just as long as it accommodates the CaC rule with the most usage across profiles, right?

> I also am not very keen on keeping a table just to reference different compliance standards... seems to me like a lot of duplication. So... I'd like to see if other folks have other ideas. @jhrozek anything on your side?

Are you referring to the `profile` table?

**Comment by rhmdnd** [comment]
The hierarchical subject idea is interesting.

> this way, it would be a lot easier to specify where stuff belongs to. An alternative is to make the parent_id be part of the metadata.

Can you elaborate on this a little more? For example, are you suggesting that we would have a subject for the cluster, which would have child subjects for nodes?

**Comment by rhmdnd** [comment]
At what depth do you anticipate the hierarchy? It's easy to think of a simple case where a cluster is the parent and each node is a child, resulting in tree with the height of 1 (assuming 0 is the first layer).

Do you anticipate an immediate need for a layer in between the nodes and the cluster (e.g., organized by service)?

**Comment by rhmdnd** [comment]
> Do you anticipate an immediate need for a layer in between the nodes and the cluster (e.g., organized by service)?

Answered in the comment above showing the example of a hierarchical relationship between the cluster, node pool, and nodes.

**Comment by rhmdnd** [comment]
@JAORMX proposed a general idea to add a FK for the subject table so that we can build hierarchies. Let me know what you think.

Also, one thing that came up in discussion is how strict we should valid the results. It's expected that if someone were to try to send results with a field longer than what the database could accommodate, the service should fail to ingest that result, right?

**Comment by rhmdnd** [comment]
We could also move the `description` to the `metadata` table, since it could be used for other things outside `results`.

Another thing to think about is that currently results from the Compliance Operator have `descriptions` and `instructions`. We might consider adding another column to the `results` schema to account for this.

**Comment by JAORMX** [comment]
> @JAORMX proposed a general idea to add a FK for the subject table so that we can build hierarchies. Let me know what you think.
> 
> Also, one thing that came up in discussion is how strict we should valid the results. It's expected that if someone were to try to send results with a field longer than what the database could accommodate, the service should fail to ingest that result, right?

It is expected and we should fail, but we should accommodate for storing these results somehow. I suggest failing for now but making these failures visible in such a way we can detect this (metrics perhaps?). We certainly don't want to loose information and want to evaluate cases as they arise.

**Comment by JAORMX** [comment]
> We could also move the `description` to the `metadata` table, since it could be used for other things outside `results`.
> 
> Another thing to think about is that currently results from the Compliance Operator have `descriptions` and `instructions`. We might consider adding another column to the `results` schema to account for this.

I agree. It's very relevant for auditors and operators to know what to do with failing results, how to evaluate the issue and how to address/fix the issue.

**Comment by rhmdnd** [comment]
> It is expected and we should fail, but we should accommodate for storing these results somehow. I suggest failing for now but making these failures visible in such a way we can detect this (metrics perhaps?). We certainly don't want to loose information and want to evaluate cases as they arise.

To clarify, this would require some alerting machinery inside the service, correct?

**Comment by rhmdnd** [comment]
> I agree. It's very relevant for auditors and operators to know what to do with failing results, how to evaluate the issue and how to address/fix the issue.

I addressed this in the updated schemas.

**Comment by JAORMX** [comment]
> > It is expected and we should fail, but we should accommodate for storing these results somehow. I suggest failing for now but making these failures visible in such a way we can detect this (metrics perhaps?). We certainly don't want to loose information and want to evaluate cases as they arise.
> 
> To clarify, this would require some alerting machinery inside the service, correct?

that's right, we'd need to start supporting metrics (probably as a prometheus-friendly endpoint)

**Comment by rhmdnd** [comment]
> that's right, we'd need to start supporting metrics (probably as a prometheus-friendly endpoint)

I pulled this into its own issue https://github.com/rhmdnd/compserv/issues/107

**Comment by rhmdnd** [comment]
Since I just proposed patches that include foreign keys. How do we want to handle foreign key relationships when an entity is deleted?

For example, say we have a foreign key between `results.subject_id` and `subject.id`. If or when the subject is deleted, should all results associated to that subject be deleted, too?

Since we're dealing with compliance data, I'm hesitant to delete data since the service may track data for long periods of time (longer than the lifecycle of a cluster).

Thoughts on how we should handle this?

**Comment by JAORMX** [comment]
I agree with your concern. We should not delete data, but have the means to display subsets instead. I recall we had something similar in barbican, where we'd "disable" an entry

**Comment by rhmdnd** [comment]
> I agree with your concern. We should not delete data, but have the means to display subsets instead. I recall we had something similar in barbican, where we'd "disable" an entry

Some projects treated "disable" like a soft delete. Should we support soft-deletes?

**Comment by rhmdnd** [comment]
I added a separate patch to call out how we should handle common things like UUIDs and datetimes. It's only a documentation patch but it makes doing some work here more consistent.

https://github.com/rhmdnd/compserv/pull/111

**Comment by rhmdnd** [comment]
Opened a separate issue to document the need for a table dedicated to assessments or scans https://github.com/rhmdnd/compserv/issues/118.

I lean towards the term `assessment` since it's more inline with terminology used by NIST.

https://pages.nist.gov/OSCAL/concepts/layer/assessment/

**Comment by rhmdnd** [comment]
# Assessment schema

An assessment is a collection of results. From the compliance-operator perspective, this is a scan. I'm leaning towards using the term `assessment` instead to be consistent with NIST terminology:

https://pages.nist.gov/OSCAL/concepts/layer/assessment/#assessment-results-model

## `id`

Required: True
Type: `UUID`
Exposed publicly: True

## `name`

Required: True
Type: `VARCHAR(255)`
Exposed publicly: True

A name for the assessment, but it doesn't have to be unique (`fedramp-high-scan`).

## `metadata_id`

Required: False
Type: `UUID`
Exposed publicly: False

This would be a foreign key to `metadata.id` table/column, used to link additional, common attributes to assessments (like created at and updated at times).

**Comment by jhrozek** [comment]
> > @JAORMX proposed a general idea to add a FK for the subject table so that we can build hierarchies. Let me know what you think.
> > Also, one thing that came up in discussion is how strict we should valid the results. It's expected that if someone were to try to send results with a field longer than what the database could accommodate, the service should fail to ingest that result, right?
> 
> It is expected and we should fail, but we should accommodate for storing these results somehow. I suggest failing for now but making these failures visible in such a way we can detect this (metrics perhaps?). We certainly don't want to loose information and want to evaluate cases as they arise.

Isn't it better to persist the result with the attribute truncated to the length we allow AND issue a warning?

**Comment by jhrozek** [comment]
> # Assessments schema
> 
> An assessment is a collection of results. From the compliance-operator perspective, this is a scan. I'm leaning towards using the term `assessment` instead to be consistent with NIST terminology:

This is useful, but how does an assessment link to the result?

**Comment by jhrozek** [comment]
> > # Assessments schema
> > An assessment is a collection of results. From the compliance-operator perspective, this is a scan. I'm leaning towards using the term `assessment` instead to be consistent with NIST terminology:
> 
> This is useful, but how does an assessment link to the result?

Nevermind, I just looked at PR #109 and noticed that the result has an assessment ID. This looks good!

I wonder if you think that the results should link to the subjects directly or through an assessment? (Genuine q., I don't have a lot of experience designing SQL tables). Naively it feels like you would always "assess a subject".

**Comment by jhrozek** [comment]
> ## `instruction`
> 
> Required: False Type: `TEXT` Exposed publicly: True
> 
> Useful to storing additional instructions for a particular rule. Many of the existing rules in the ComplinaceAsCode content store instructions that are used to communicate what actions should be done based on a finding. Aggregating this information is important for consumers of this service.
> 
> An alternative name for this could be `rationale`.

So is this:
 - why are we doing the check
 - what are we checking
 - how to remediate the finding

Instructions sounds like "what are we checking", but the alternative name you proposed (rationale) sounds like "why are we checking" and the text ("what actions should be done based on a finding") sounds like the last option.

Or were you thinking about combining them all?

**Comment by rhmdnd** [comment]
> If you want to include all references, then it's not going to be enough, for very popular rules (like `package_audit_installed`) the list of references is ~1500 chars. I guess 2048 or 4096 to be on the safe side would be enough.

Ok - that's a good point.

If we increase the length, are we assuming that we would be persisting a list? If so, we should consider separating those values out into a different table so we don't violate first normal form.

**Comment by rhmdnd** [comment]
> Isn't it better to persist the result with the attribute truncated to the length we allow AND issue a warning?

Ok - maybe truncation is the devil we have to deal with then in this case if we need to persist something.

**Comment by rhmdnd** [comment]
> This is useful, but how does an assessment link to the result?

The way I'm thinking about this is that an assessment as a one to many relationship with results. Each result must link to an assessment through a foreign key relationship. The assessment would store information like scan time and ID, which are applicable to all results from the report.

**Comment by jhrozek** [comment]
On Wed, Aug 03, 2022 at 06:38:44AM -0700, Lance Bragstad wrote:
> > If you want to include all references, then it's not going to be enough, for very popular rules (like `package_audit_installed`) the list of references is ~1500 chars. I guess 2048 or 4096 to be on the safe side would be enough.
> 
> Ok - that's a good point.
> 
> If we increase the length, are we assuming that we would be persisting a list? If so, we should consider separating those values out into a different table so we don't violate first normal form.

Hmm, I think it is concievable that someone would want to query results
that pertain to a single control. I think I remember ACM had mentioned
this use-case. So splitting the references to a separate table would
probably at least give us enough room to design something better than a
blob.

**Comment by rhmdnd** [comment]
> Nevermind, I just looked at PR #109 and noticed that the result has an assessment ID. This looks good!
> 
> I wonder if you think that the results should link to the subjects directly or through an assessment? (Genuine q., I don't have a lot of experience designing SQL tables). Naively it feels like you would always "assess a subject".

Good question. I think we could do either.

Linking the assessment to the subject reduces duplication across all results rows related to that assessment. Linking the result to the subject gives us the flexibility to have subjects differ, or link to different components of the system.

**Comment by jhrozek** [comment]
On Wed, Aug 03, 2022 at 06:42:34AM -0700, Lance Bragstad wrote:
> > Isn't it better to persist the result with the attribute truncated to the length we allow AND issue a warning?
> 
> Ok - maybe truncation is the devil we have to deal with then in this case if we need to persist something.

Sorry, maybe I was unclear, I was trying to say that from a user
perspective, it seems preferable to know that my cluster is out of
compliance even if the instructions would be incomplete than having no
record of the issue peristing.

**Comment by rhmdnd** [comment]
> So is this:
> 
>     * why are we doing the check
> 
>     * what are we checking
> 
>     * how to remediate the finding
> 
> 
> Instructions sounds like "what are we checking", but the alternative name you proposed (rationale) sounds like "why are we checking" and the text ("what actions should be done based on a finding") sounds like the last option.
> 
> Or were you thinking about combining them all?

Good point. Initially, I only wanted to create schemas for what we would use, but it sounds like it's useful (based on your definitions) to have `instructions`, `rationale`, and `description` since they all fill a unique purpose. Additionally, putting rationale in the instructions will probably complicate things for callers. For example, if someone asked for the result instructions, they would have to parse the different portions of it into rationale and instructions (which arguably violates first normal form).

I can propose a separate, null-able column for `rationale`. It's available for us if we need it and the compliance service can use it.

**Comment by jhrozek** [comment]
On Wed, Aug 03, 2022 at 06:53:31AM -0700, Lance Bragstad wrote:
> > So is this:
> > 
> >     * why are we doing the check
> > 
> >     * what are we checking
> > 
> >     * how to remediate the finding
> > 
> > 
> > Instructions sounds like "what are we checking", but the alternative name you proposed (rationale) sounds like "why are we checking" and the text ("what actions should be done based on a finding") sounds like the last option.
> > 
> > Or were you thinking about combining them all?
> 
> Good point. Initially, I only wanted to create schemas for what we would use, but it sounds like it's useful (based on your definitions) to have `instructions`, `rationale`, and `description` since they all fill a unique purpose. Additionally, putting rationale in the instructions will probably complicate things for callers. For example, if someone asked for the result instructions, they would have to parse the different portions of it into rationale and instructions (which arguably violates first normal form).
> 
> I can propose a separate, null-able column for `rationale`. It's available for us if we need it and the compliance service can use it.

This sounds good!

**Comment by rhmdnd** [comment]
# Control schema

A control would be a reference to a control as written by a standards body (NIST or CIS).

## `id`

Required: True
Type: `UUID`
Exposed publicly: True

## `name`

Required: True
Type: `VARCHAR(255)`
Exposed publicly: True

A name for the control.

## `metadata_id`

Required: False
Type: `UUID`
Exposed publicly: False

This would be a foreign key to `metadata.id` table/column, used to link additional, common attributes (like description, created at, and updated at times).

## `profile_id`

Required: True
Type: `UUID`
Exposed publicly: True

This would be a foreign key to `profile.id` table/column, used to reference the profile or baseline for the control.

## `severity`

Required: True
Type: `VARCHAR(50)`
Exposed publicly: True

This is an optional parameter that denotes the severity of a particular control (e.g., `high`, `medium`, `low`).

**Comment by rhmdnd** [comment]
# Profile schema

A profile references a benchmark containing controls (CIS benchmarks for OpenShift, FedRAMP High).

## `id`

Required: True
Type: `UUID`
Exposed publicly: True

## `name`

Required: True
Type: `VARCHAR(255)`
Exposed publicly: True

A name for the control.

## `metadata_id`

Required: False
Type: `UUID`
Exposed publicly: False

This would be a foreign key to `metadata.id` table/column, used to link additional, common attributes (like description, created at, and updated at times).

**Comment by rhmdnd** [comment]
> Not sure if I should ask here or in PR#128, but can you give me an example of a row in the controls table? I'm mostly wondering about what's in the name, is it the plain english "title" of the control (e.g. auditing must be enabled) or the control's ID (std.1.2.3)?

Actually - if we just reference the control group, the name is redundant (assuming we can derive it from the actual benchmark or profile).

But, an example with the name would look like:

```
control.id = "158d705f-dcc6-451a-afff-68497253a27b"
control.name = "Ensure that the --authorization-mode argument is not set to AlwaysAllow"
control.group = "4.2.2"
control.metadata_id = "994f01b1-db54-4066-b0a3-bffe2ea7afed"
control.profile_id = "c98d799e-1b29-4897-b26a-58dcfa33f1fb"
```

Alternatively, if we completely omit the name, we would have:

```
control.id = "158d705f-dcc6-451a-afff-68497253a27b"
control.group = "4.2.2"
control.metadata_id = "994f01b1-db54-4066-b0a3-bffe2ea7afed"
control.profile_id = "c98d799e-1b29-4897-b26a-58dcfa33f1fb"
```

Then, we would need something to derive the name from the benchmark, which we will probably need anyway to derive other pieces of information.

**Comment by rhmdnd** [comment]
# Catalog schema

A catalog is a pristine copy of a benchmark, containing controls, as written by the benchmark author (NIST, CIS).

## `id`

Required: True
Type: `UUID`
Exposed publicly: True

## `name`

Required: True
Type: `VARCHAR(255)`
Exposed publicly: True

A name for the catalog (e.g., `NIST SP 800-53`).

## `metadata_id`

Required: False
Type: `UUID`
Exposed publicly: False

This would be a foreign key to `metadata.id` table/column, used to link additional, common attributes (like description, created at, and updated at times).

## `content`

Required: True
Type: `TEXT`
Exposed publicly: True

This would be a free-from field for storing catalogs, as provided by a standards body. An example of the NIST SP 800-53 catalog would be:

https://github.com/usnistgov/oscal-content/tree/main/nist.gov/SP800-53/rev5
